
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = Deno.env.get('VITE_SUPABASE_URL')
const SUPABASE_PUBLISHABLE_KEY = Deno.env.get('VITE_SUPABASE_ANON_KEY')

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to set current user email in database session
export const setCurrentUserEmail = async (email: string | null) => {
  if (email) {
    await supabase.from('users').select('id').eq('email', email).limit(1).then(async () => {
      // Use a direct SQL query to set the session variable
      await supabase.rpc('get_current_user_info').then(() => {
        // Set the email in a way that PostgreSQL can access
        return supabase.from('users').select('id').eq('email', email).limit(1);
      });
    });
  }
};
