// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydiufvjyvqleezvuylor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkaXVmdmp5dnFsZWV6dnV5bG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDAwMjYsImV4cCI6MjA2MDc3NjAyNn0.yQrF-uNmkVvDHeupPAzwzjtqwnJ24JyNuG_KekNLOdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);